using System;
using System.Collections.Generic;
using System.Text;
using ToolKitV.ViewModels;

namespace ToolKitV.Models
{
    public static class SirenGenerator
    {
        // ─── Common preset patterns (32 bools each) ──────────────────────────────

        /// <summary>10101010… alternating — classic two-way alternating flash</summary>
        public static readonly bool[] Alternating = GenerateAlternating();

        /// <summary>11110000… steady on/off — slow pulse</summary>
        public static readonly bool[] SlowPulse = GenerateSlowPulse();

        /// <summary>11001100… double-flash</summary>
        public static readonly bool[] DoubleFlash = GenerateDoubleFlash();

        /// <summary>All on — steady burn</summary>
        public static readonly bool[] SteadyOn = GenerateSteadyOn();

        /// <summary>Random-feeling rapid burst then pause</summary>
        public static readonly bool[] RapidBurst = GenerateRapidBurst();

        // ─── XML generation ──────────────────────────────────────────────────────

        /// <summary>
        /// Generates a carcols.meta XML snippet from a list of SirenRow objects.
        /// Each siren gets a readable hex + binary comment so devs can verify patterns.
        /// </summary>
        public static string GenerateCarcols(IList<SirenRow> rows, string vehicleName = "your_vehicle")
        {
            var sb = new StringBuilder();
            sb.AppendLine("<!-- Paste inside your <Item> element in carcols.meta -->");
            sb.AppendLine($"<!-- Vehicle: {vehicleName} | Generated by TGToolKit Siren Builder -->");
            sb.AppendLine("<sirens>");

            for (int i = 0; i < rows.Count; i++)
            {
                SirenRow row = rows[i];
                uint seq = row.GetSequenceInteger();

                string binary = Convert.ToString((long)seq, 2).PadLeft(32, '0');
                string hex    = $"0x{seq:X8}";

                sb.AppendLine($"  <!-- {row.LightName} | {hex} | {binary} -->");
                sb.AppendLine("  <Item>");
                sb.AppendLine($"    <id value=\"{i + 1}\"/>");
                sb.AppendLine("    <flags value=\"0\"/>");
                sb.AppendLine("    <lightFalloffMax value=\"15.0\"/>");
                sb.AppendLine("    <lightFalloffExponent value=\"30.0\"/>");
                sb.AppendLine("    <lightInnerConeAngle value=\"0.0\"/>");
                sb.AppendLine("    <lightOuterConeAngle value=\"90.0\"/>");
                sb.AppendLine("    <lightOffset x=\"0.0\" y=\"0.0\" z=\"0.0\"/>");
                sb.AppendLine("    <lightColor r=\"255\" g=\"0\" b=\"0\"/>");
                sb.AppendLine("    <lightIntensity value=\"2.0\"/>");
                sb.AppendLine("    <lightGroup value=\"0\"/>");
                sb.AppendLine($"    <sequencerBpm value=\"600\"/>");
                sb.AppendLine("    <startDelay value=\"0\"/>");
                sb.AppendLine("    <sirenOrLight value=\"false\"/>");
                sb.AppendLine("    <healthOcclusionInfo value=\"0\"/>");
                sb.AppendLine("    <useRealLights value=\"true\"/>");
                sb.AppendLine("    <flashiness>");
                sb.AppendLine($"      <delta value=\"{seq}\"/>");
                sb.AppendLine("    </flashiness>");
                sb.AppendLine("  </Item>");
            }

            sb.AppendLine("</sirens>");
            return sb.ToString();
        }

        // ─── Pattern generators ──────────────────────────────────────────────────

        private static bool[] GenerateAlternating()
        {
            var p = new bool[32];
            for (int i = 0; i < 32; i++) p[i] = i % 2 == 0;
            return p;
        }

        private static bool[] GenerateSlowPulse()
        {
            var p = new bool[32];
            for (int i = 0; i < 32; i++) p[i] = i % 8 < 4;
            return p;
        }

        private static bool[] GenerateDoubleFlash()
        {
            var p = new bool[32];
            for (int i = 0; i < 32; i++) p[i] = i % 4 < 2;
            return p;
        }

        private static bool[] GenerateSteadyOn()
        {
            var p = new bool[32];
            for (int i = 0; i < 32; i++) p[i] = true;
            return p;
        }

        private static bool[] GenerateRapidBurst()
        {
            // 3 fast flashes then an 8-tick pause, repeating
            var p = new bool[32];
            int[] on = { 0, 2, 4 };
            for (int i = 0; i < 32; i++)
            {
                int pos = i % 16;
                p[i] = pos == 0 || pos == 2 || pos == 4;
            }
            return p;
        }
    }
}
